# Generated by Django 2.2 on 2020-09-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='products',
        ),
        migrations.AddField(
            model_name='bill',
            name='products',
            field=models.ManyToManyField(to='api.Product'),
        ),
    ]
