# Generated by Django 2.2 on 2020-09-14 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200914_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descriptionbill',
            old_name='products',
            new_name='product',
        ),
    ]
