# Generated by Django 2.2 on 2020-09-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200919_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderDescription',
        ),
        migrations.AddField(
            model_name='order',
            name='orderDescription',
            field=models.ManyToManyField(to='api.OrderDescription'),
        ),
    ]
