# Generated by Django 2.2 on 2020-09-19 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200919_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderDescription',
        ),
        migrations.AddField(
            model_name='order',
            name='orderDescription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.OrderDescription'),
            preserve_default=False,
        ),
    ]
