# Generated by Django 2.2 on 2020-09-19 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200919_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderDescription',
        ),
        migrations.AddField(
            model_name='orderdescription',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Order'),
            preserve_default=False,
        ),
    ]
