# Generated by Django 2.2 on 2020-09-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200919_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdescription',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='order_description',
            field=models.ManyToManyField(to='api.OrderDescription'),
        ),
    ]
