# Generated by Django 2.2 on 2020-09-20 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200919_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_description',
        ),
        migrations.AddField(
            model_name='order',
            name='order_description',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.OrderDescription'),
            preserve_default=False,
        ),
    ]
