# Generated by Django 2.2 on 2020-09-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200920_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_description',
        ),
        migrations.AddField(
            model_name='order',
            name='order_description',
            field=models.ManyToManyField(to='api.OrderDescription'),
        ),
    ]
