# Generated by Django 2.2 on 2020-09-20 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200920_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_description',
        ),
        migrations.AddField(
            model_name='orderdescription',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
