# Generated by Django 2.2 on 2020-09-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200920_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type_order',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
