# Generated by Django 2.2 on 2020-09-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_order_type_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type_order',
            field=models.CharField(max_length=1),
        ),
    ]
