# Generated by Django 2.2 on 2020-09-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_order_type_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdescription',
            name='order',
        ),
        migrations.AddField(
            model_name='orderdescription',
            name='order',
            field=models.ManyToManyField(to='api.Order'),
        ),
    ]
