# Generated by Django 2.2 on 2020-09-21 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200921_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdescription',
            name='order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Order'),
        ),
    ]
