# Generated by Django 2.2 on 2020-09-21 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200921_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdescription',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Order'),
        ),
    ]
