# Generated by Django 2.2 on 2020-09-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200921_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdescription',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='orderDescription',
            field=models.ManyToManyField(to='api.OrderDescription'),
        ),
    ]
