# Generated by Django 2.2 on 2020-09-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200921_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderDescription',
            field=models.ManyToManyField(blank=True, null=True, to='api.OrderDescription'),
        ),
    ]
