# Generated by Django 2.2 on 2020-09-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200921_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderDescription',
            field=models.ManyToManyField(to='api.OrderDescription'),
        ),
    ]
