# Generated by Django 2.2 on 2020-09-21 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200921_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderDescription',
        ),
        migrations.AddField(
            model_name='orderdescription',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Order'),
            preserve_default=False,
        ),
    ]
